security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        fetcher:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: fetcher
            jwt: ~

    access_control:
        - { path: ^/api/catalog, roles: PUBLIC_ACCESS }
        - { path: ^/api/search, roles: PUBLIC_ACCESS }
        - { path: ^/api/check-email, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/metro_list, roles: PUBLIC_ACCESS }
        - { path: ^/api/hair_colors, roles: PUBLIC_ACCESS }
        - { path: ^/api/search/additional-options, roles: PUBLIC_ACCESS }
        - { path: ^/api/district_list, roles: PUBLIC_ACCESS }
        - { path: ^/api/sign-up, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
